Repository cyberark/secretless-broker, pull requests merged in 2018-12, with the labels that each got.

#531 DO NOT MERGE: plan for TLS Support for Database Handlers
  CONTRIBUTING.md
  design/tls-support-plan.md
  docs/docs/reference/handlers/postgres.md
Labels: implementing, in progress

#551 Update the keychain provider test
  CONTRIBUTING.md
  Dockerfile
  Dockerfile.dev
  Dockerfile.test
  README.md
  demos/k8s-demo/04_test_deployment.sh
  demos/k8s-demo/README.md
  go.sum
  resource-definitions/README.md
  test/manual/keychain_provider/test
Labels: implementing, in progress

#563 Add blog post for Secretless team at KubeCon
  docs/_posts/2018-12-06-meet-us-at-kubecon.md
  docs/_sass/_elements.scss
  docs/img/secretless_at_kubecon_2018.png
Labels: implementing, in progress

#565 Update footer link for Google Group
  docs/_includes/footer.html
Labels: component/website, implementing, in progress

#539 Postgres Handler supports TLS defaulting to sslmode=require
  .gitlab-ci.yml
  docs/docs/reference/handlers/postgres.md
  go.sum
  internal/app/secretless/handlers/pg/backend.go
  internal/app/secretless/handlers/pg/handler.go
  internal/app/secretless/handlers/pg/ssl.go
  internal/app/secretless/handlers/pg/ssl_permissions.go
  test/pg_handler/Dockerfile.pg
  test/pg_handler/docker-compose.yml
  test/pg_handler/etc/server.crt
  test/pg_handler/etc/server.key
  test/pg_handler/pg_test.go
  test/pg_handler/run_dev
  test/pg_handler/secretless.dev.yml
  test/pg_handler/secretless.yml
  test/pg_handler/start
  test/pg_handler/start_dev
  test/pg_handler/wait-for-pg
Labels: in progress, reviewing

#564 mysql handler supports sslmode up to verify-ca
  .gitignore
  Dockerfile
  Dockerfile.dev
  bin/reflex
  go.sum
  internal/app/secretless/handlers/mysql/backend.go
  internal/app/secretless/handlers/mysql/protocol/ssl.go
  test/mysql_handler/.gitignore
  test/mysql_handler/README.md
  test/mysql_handler/dev
  test/mysql_handler/docker-compose.yml
  test/mysql_handler/fixtures_static/invalid-ca.pem
  test/mysql_handler/mysql_test.go
  test/mysql_handler/pkg/run_test_case.go
  test/mysql_handler/secretless.yml
  test/mysql_handler/start
  test/mysql_handler/stop
  test/mysql_handler/test
  test/mysql_handler/tests/essentials_test.go
  test/mysql_handler/tests/init_test.go
  test/mysql_handler/tests/ssl_test.go
  test/mysql_handler/wait-for-mysql
  test/mysql_handler/wait-for-secretless
  test/util/test/cmd/generate_secretless_yml.go
  test/util/test/config_generator.go
  test/util/test/init.go
  test/util/test/live_configuration.go
  test/util/test/run_test_case.go
  test/util/test/test_case.go
  test/util/test/types.go
  test/util/test/utils.go
Labels: implementing, in progress

#572 CPU and Memory profiling and documentation have been added (P2)
  CONTRIBUTING.md
  bin/cpu_profiling
  bin/memory_profiling
  cmd/secretless-broker/main.go
  go.mod
  go.sum
  internal/pkg/plugin/manager.go
Labels: implementing, in progress
