Repository cyberark/secretless-broker, pull requests merged in 2018-11, with the labels that each got.

#499 A bit of refactoring and cleanup
  bin/test_unit
  go.sum
  internal/app/secretless/handlers/pg/backend.go
  internal/pkg/util/util.go
Labels: in progress

#496 Mobile nav fixes, removed search, and updated google tag manager
  docs/_includes/head.html
  docs/_includes/top_nav_home.html
  docs/_layouts/default.html
  docs/_layouts/subpages.html
  docs/_sass/_buttons.scss
  docs/_sass/_navbar.scss
  docs/_sass/_variables.scss
  docs/community.md
Labels: in progress

#504 503 - Dropdown fixes
  docs/_sass/_navbar.scss
Labels: implementing, in progress

#502 Fix mobile nav dropdown overlap issue
  docs/_includes/head.html
  docs/_includes/top_nav_home.html
  docs/_layouts/default.html
  docs/_layouts/subpages.html
  docs/_sass/_buttons.scss
  docs/_sass/_navbar.scss
  docs/_sass/_variables.scss
  docs/community.md
Labels: implementing, in progress

#32 Secretless has a provider for aws secrets manager
  go.mod
  go.sum
  internal/app/secretless/providers/awssecrets/provider.go
  internal/app/secretless/providers/providers.go
  test/aws_secrets_provider/README.md
  test/aws_secrets_provider/aws_secrets_provider_test.go
  test/aws_secrets_provider/docker-compose.yml
  test/aws_secrets_provider/start
  test/aws_secrets_provider/stop
  test/aws_secrets_provider/test
Labels: component/secretless-providers, implementing

#513 Add release instructions to README
  README.md
Labels: implementing, in progress

#517 fix(pipeline): add missing and fix broken tags
  bin/build
  bin/build_utils
  bin/publish
Labels: implementing, in progress

#523 Only save the latest build locally in GitLab
  .gitlab-ci.yml
Labels: implementing, in progress

#516 fix(k8s provider): use non-empty current namespace to fetch secrets
  internal/app/secretless/providers/kubernetessecrets/client.go
  internal/app/secretless/providers/kubernetessecrets/provider.go
  test/kubernetes_provider/kubernetes_provider_test.go
Labels: implementing, in progress

#524 Add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: implemented, in progress

#528 Update broken keychain provider test
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  internal/app/secretless/providers/keychain/osx.go
  test/keychain_provider/keychain_provider_test.go
  test/manual/k8s_crds/deploy
  test/manual/k8s_crds/deployment.yaml
  test/manual/k8s_crds/first-v1.yaml
  test/manual/k8s_crds/first-v2.yaml
  test/manual/k8s_crds/stop_deployment
  test/manual/keychain_provider/README.md
  test/manual/keychain_provider/keychain_provider_test.go
  test/manual/keychain_provider/load_test_env_vars
  test/manual/keychain_provider/start
  test/manual/keychain_provider/stop
  test/manual/keychain_provider/test
Labels: implementing, in progress

#532 Bumping to version 0.5.2
  CHANGELOG.md
  VERSION
Labels: implementing, in progress

#529 refactor(pipeline): allow ./bin/test_integration to specify individual test_folders
  bin/test_integration
Labels: implemented, in progress
