Repository cyberark/secretless-broker, pull requests merged in 2018-08, with the labels that each got.

#299 Update Jenkinsfile to publish master to staging site
  Jenkinsfile
Labels: in progress

#300 Turn off maintenance mode
  docs/_config.yml
Labels: in progress

#283 DO NOT MERGE UNTIL RELEASE DATE! Made the publish step publish to DockerHub
  bin/publish
  demos/k8s-demo/03_deploy_app.sh
  demos/k8s-demo/etc/quick-start.yml
Labels: in progress

#301 Do the docker push
  bin/publish
Labels: in progress

#287 Graphics update & Analytics
  README.md
  docs/_includes/footer.html
  docs/_includes/head.html
  docs/_includes/jumbotron.html
  docs/_layouts/default.html
  docs/_layouts/landing.html
  docs/_layouts/subpages.html
  docs/_sass/_defaults.scss
  docs/_sass/_elements.scss
  docs/_sass/_footer.scss
  docs/_sass/_media.scss
  docs/_sass/_variables.scss
  docs/community.md
  docs/docs/overview/how_it_works.md
  docs/favicon-16x16.png
  docs/favicon-32x32.png
  docs/favicon-96x96.png
  docs/favicon.ico
  docs/img/secretless_architecture.svg
  docs/img/traditional_architecture.svg
  docs/index.md
Labels: component/website, in progress

#296 Add a third tier toggle option to side-navbar for docs
  docs/_includes/side_navigation.html
  docs/_layouts/docs.html
  docs/_sass/_navbar.scss
  docs/javascript/secretless.js
Labels: in progress

#302 Fixed linting errors with the codebase
  Jenkinsfile
  internal/app/secretless/listeners/http/listener.go
  internal/app/secretless/providers/keychain/osx.go
  internal/pkg/plugin/resolver.go
  internal/pkg/plugin/resolver_test.go
Labels: in progress

#297 Navigation updates: active nav links & homepage dropdown style
  docs/_data/navigation.yml
  docs/_includes/side_navigation.html
  docs/_includes/top_nav.html
  docs/_includes/top_nav_home.html
  docs/_sass/_elements.scss
  docs/_sass/_navbar.scss
  docs/docs/faq.md
  docs/docs/get_started.md
  docs/docs/get_started/deploy_to_kubernetes.md
  docs/docs/get_started/quick_start.md
  docs/docs/overview.md
  docs/docs/overview/how_it_works.md
  docs/docs/overview/key_terms.md
  docs/docs/overview/security.md
  docs/docs/overview/why_secretless.md
  docs/docs/reference.md
  docs/docs/reference/handlers.md
  docs/docs/reference/handlers/http/aws.md
  docs/docs/reference/handlers/http/basic.md
  docs/docs/reference/handlers/http/conjur.md
  docs/docs/reference/handlers/mysql.md
  docs/docs/reference/handlers/postgres.md
  docs/docs/reference/handlers/ssh.md
  docs/docs/reference/handlers/ssh_agent.md
  docs/docs/reference/how_to_deploy.md
  docs/docs/reference/listeners.md
  docs/docs/reference/providers.md
  docs/docs/reference/providers/conjur.md
  docs/docs/reference/providers/env.md
  docs/docs/reference/providers/file.md
  docs/docs/reference/providers/keychain.md
  docs/docs/reference/providers/literal.md
  docs/docs/reference/providers/vault.md
Labels: component/website, in progress

#309 Added Goreleaser for automated binary archive building (for tags)
  .goreleaser.yml
  bin/Dockerfile.releaser
  bin/build_release
Labels: in progress

#290 feat: handlers informs clients of close connections and secretless shutdown
  internal/app/secretless/handlers/http/aws.go
  internal/app/secretless/handlers/http/basic_auth.go
  internal/app/secretless/handlers/http/conjur.go
  internal/app/secretless/handlers/mysql/backend.go
  internal/app/secretless/handlers/mysql/handler.go
  internal/app/secretless/handlers/pg/backend.go
  internal/app/secretless/handlers/pg/handler.go
  internal/app/secretless/handlers/ssh/handler.go
  internal/app/secretless/handlers/sshagent/handler.go
  internal/app/secretless/listeners/http/listener.go
  internal/app/secretless/listeners/mysql/listener.go
  internal/app/secretless/listeners/pg/listener.go
  internal/app/secretless/listeners/ssh/listener.go
  internal/app/secretless/listeners/sshagent/listener.go
  internal/app/secretless/proxy.go
  internal/pkg/plugin/manager.go
  pkg/secretless/plugin/v1/handler.go
  pkg/secretless/plugin/v1/listener.go
  test/plugin/example/backend.go
  test/plugin/example/handler.go
  test/plugin/example/listener.go
Labels: in progress

#310 fix: Proxy#Run SHUTDOWN event deadlock
  internal/app/secretless/proxy.go
Labels: in progress

#313 fix: pg_test.go TCP requires sslmode=disable
  test/pg_handler/pg_test.go
Labels: in progress

#311 WIP - Cleaned up channel closing in main roxy loop
  internal/app/secretless/proxy.go
Labels: in progress

#312 feat: add kubernetes secrets provider
  go.mod
  go.sum
  internal/app/secretless/providers/kubernetes-secrets/client.go
  internal/app/secretless/providers/kubernetes-secrets/provider.go
  internal/app/secretless/providers/providers.go
Labels: in progress

#319 Fixed soft-reload 100% CPU bug
  internal/app/secretless/handlers/mysql/handler.go
  internal/app/secretless/handlers/pg/handler.go
  internal/app/secretless/listeners/mysql/listener.go
  internal/app/secretless/listeners/pg/listener.go
  internal/app/secretless/listeners/ssh/listener.go
  internal/app/secretless/listeners/sshagent/listener.go
  pkg/secretless/plugin/v1/listener.go
Labels: review

#327 Minor styling and content fixes to the website
  docs/_data/navigation.yml
  docs/_includes/footer.html
  docs/_includes/jumbotron.html
  docs/_layouts/landing.html
  docs/docs/faq.md
  docs/docs/get_started/quick_start.md
  docs/docs/overview.md
  docs/index.md
Labels: in progress

#246 Added ability for Secretless to watch for configuration file changes
  cmd/secretless-broker/main.go
  go.mod
  go.sum
  internal/pkg/plugin/fs_watcher.go
  internal/pkg/plugin/manager.go
Labels: in progress

#330 Removed the need for realpath (coreutils)
  bin/abspath
  bin/build
  bin/build_release
  bin/build_website
  bin/check_website_links
  bin/publish_website
  bin/test_quickstart
  bin/test_unit
Labels: in progress

#341 push sidecar-injector image to dockerhub as part of CI/CD
  Jenkinsfile
  sidecar-injector/README.md
  sidecar-injector/bin/build_sidecar_injector.sh
  sidecar-injector/bin/publish
  sidecar-injector/deployment/deployment.yaml
  sidecar-injector/pkg/inject/common.go
Labels: in progress

#339 Change PX units to REM units
  docs/_sass/_defaults.scss
  docs/_sass/_elements.scss
  docs/_sass/_navbar.scss
  docs/_sass/_variables.scss
Labels: review

#331 Keep side navbar section open on page reload
  docs/_data/navigation.yml
  docs/_includes/side_navigation.html
  docs/_sass/_navbar.scss
  docs/docs/reference/how_to_deploy.md
  docs/docs/reference/how_to_deploy_conjur.md
  docs/docs/reference/providers/conjur.md
  docs/docs/reference/providers/env.md
  docs/docs/reference/providers/file.md
  docs/docs/reference/providers/keychain.md
  docs/docs/reference/providers/literal.md
  docs/docs/reference/providers/vault.md
  docs/javascript/secretless.js
Labels: review

#351 fix: avoid out of bounds panic by validating kubernetes secret id
  internal/app/secretless/providers/kubernetes-secrets/provider.go
Labels: in progress

#346 Sidebar-updates
  docs/_data/navigation.yml
  docs/_includes/footer.html
  docs/_includes/top_nav.html
  docs/_includes/top_nav_home.html
  docs/_layouts/default.html
  docs/_layouts/docs.html
  docs/_layouts/landing.html
  docs/_sass/_defaults.scss
  docs/_sass/_elements.scss
  docs/_sass/_grid.scss
  docs/_sass/_navbar.scss
  docs/css/secretless.scss
  docs/docs/faq.md
  docs/docs/overview/how_it_works.md
  docs/docs/reference/handlers/overview.md
  docs/docs/reference/how-to-deploy/overview.md
  docs/docs/reference/how-to-deploy/using-conjur.md
  docs/docs/reference/how-to-deploy/using-kubernetes-secrets.md
  docs/docs/reference/providers/keychain.md
  docs/docs/reference/providers/overview.md
  docs/img/clipboard-focus.svg
  docs/img/slss_bg_pattern.svg
  docs/img/slss_bg_pattern_2.svg
Labels: component/website, in progress

#358 fix: avoid failing build -> set GO111MODULE=on for full-demo/myapp
  demos/full-demo/src/ansible/Dockerfile
  demos/full-demo/src/myapp/Dockerfile
  demos/quick-start/docker/Dockerfile
Labels: in progress

#350 update k8s-demo to use kubernetes-secrets provider
  demos/k8s-demo/01_create_db.sh
  demos/k8s-demo/02_configure_db.sh
  demos/k8s-demo/03_deploy_app.sh
  demos/k8s-demo/README.md
  demos/k8s-demo/admin_config.sh
  demos/k8s-demo/etc/pg.yml
  demos/k8s-demo/etc/quick-start.yml
  demos/k8s-demo/etc/secretless.yml
  demos/k8s-demo/rotate_password.sh
  demos/k8s-demo/utils.sh
Labels: in progress

#348 Add styling to ensure card features are same size
  docs/_sass/_media.scss
Labels: component/secretless-site, review

#349 Conjur handler consumes access token from Conjur provider
  internal/app/secretless/handlers/http/conjur.go
  internal/app/secretless/providers/conjur/provider.go
  internal/app/secretless/providers/env/provider.go
  internal/app/secretless/providers/file/provider.go
  internal/app/secretless/providers/keychain/provider.go
  internal/app/secretless/providers/kubernetes-secrets/provider.go
  internal/app/secretless/providers/literal/provider.go
  internal/app/secretless/providers/providers.go
  internal/app/secretless/providers/vault/provider.go
  internal/app/summon/command/command.go
  internal/pkg/plugin/manager.go
  internal/pkg/plugin/resolver.go
  test/conjur/conjur_provider_test.go
  test/plugin/example/cmd/main.go
  test/plugin/example/provider.go
  test/vault_provider/vault_provider_test.go
Labels: in progress

#357 Add k8 banner and fix dropped active class
  docs/_includes/cta-banner-integ.html
  docs/_includes/cta-banner.html
  docs/_includes/side_navigation.html
  docs/_layouts/docs.html
  docs/_sass/_elements.scss
  docs/_sass/_footer.scss
  docs/docs/get_started/quick_start.md
  docs/index.md
Labels: component/website, in progress

#359 Add test for clean listener shutdown
  pkg/secretless/plugin/v1/listener_test.go
Labels: in progress

#370 Fix linting error handling
  .dockerignore
  Jenkinsfile
  bin/check_style
  internal/app/secretless/providers/kubernetessecrets/client.go
  internal/app/secretless/providers/kubernetessecrets/provider.go
  internal/app/secretless/providers/providers.go
  test/plugin/example/conn_manager.go
Labels: in progress

#376 Convert codebase to golang v1.11.0
  Dockerfile
  Dockerfile.dev
  Dockerfile.test
  bin/Dockerfile.codegen
  bin/Dockerfile.releaser
  demos/full-demo/src/myapp/Dockerfile
  demos/full-demo/src/proxy_tls/Dockerfile
  go.sum
  sidecar-injector/Dockerfile
  test/plugin/echo/Dockerfile
Labels: in progress
