Repository cyberark/secretless-broker, pull requests merged in 2019-04, with the labels that each got.

#676 Update README.md
  README.md
Labels: in progress

#677 update demos/quick-start/README.md to use universal psql command
  .gitlab-ci.yml
  demos/quick-start/README.md
  demos/quick-start/test/bin/entrypoint
Labels: in progress, reviewing

#678 Update contributor info for documentation
  CONTRIBUTING.md
  docs/README.md
Labels: implemented, in progress

#684 Updated tutorial exists for k8s secretless
  demos/k8s-demo/README.md
  docs/_data/navigation.yml
  docs/_includes/cta-banner-integ.html
  docs/_layouts/subpages.html
  docs/_layouts/tutorials.html
  docs/_sass/_defaults.scss
  docs/_sass/_tutorial.scss
  docs/css/secretless.scss
  docs/docs/get_started/kubernetes_tutorial.md
  docs/tutorials/kubernetes/app-dev.md
  docs/tutorials/kubernetes/appendix.md
  docs/tutorials/kubernetes/finish.md
  docs/tutorials/kubernetes/kubernetes-tutorial-base.md
  docs/tutorials/kubernetes/overview.md
  docs/tutorials/kubernetes/sec-admin.md
Labels: component/secretless-ui, implementing, in progress, kind/ux

#675 Comprehensive tests exists for K8s CRDs
  test/manual/k8s_crds/.gitignore
  test/manual/k8s_crds/README.md
  test/manual/k8s_crds/deploy
  test/manual/k8s_crds/deployment.yaml.sh
  test/manual/k8s_crds/first-v1.yaml
  test/manual/k8s_crds/first-v2.yaml
  test/manual/k8s_crds/stop_deployment
Labels: implemented, in progress

#685 automated testing of CRDs
  Jenkinsfile
  internal/app/secretless/configurationmanagers/kubernetes/crd/constants.go
  k8s-ci/Dockerfile
  k8s-ci/k8s_crds/.gitignore
  k8s-ci/k8s_crds/README.md
  k8s-ci/k8s_crds/deployment.yaml.sh
  k8s-ci/k8s_crds/first.yaml.sh
  k8s-ci/k8s_crds/stop_deployment
  k8s-ci/k8s_crds/test
  k8s-ci/platform_login
  k8s-ci/secrets.yml
  k8s-ci/test
  k8s-ci/utils.sh
  pkg/apis/secretless.io/register.go
  resource-definitions/crd_injector.go
  resource-definitions/crd_watcher.go
  test/manual/k8s_crds/.gitignore
  test/manual/k8s_crds/deploy
  test/manual/k8s_crds/first-v2.yaml
  test/manual/k8s_crds/stop_deployment
Labels: implementing, in progress
