Repository cyberark/secretless-broker, pull requests merged in 2019-03, with the labels that each got.

#634 shared library exposing secret providers
  cmd/shared/.gitignore
  cmd/shared/README.md
  cmd/shared/main.cpp
  cmd/shared/main.go
  internal/app/secretless/handlers/mysql/protocol/protocol.go
  internal/app/secretless/handlers/mysql/protocol/protocol_test.go
Labels: implementing, in progress

#649 353 - Update Kubernetes Tutorial for Simplicity and Clarity
  docs/_sass/_defaults.scss
  docs/docs/get_started/kubernetes_tutorial.md
  docs/img/application_developer.jpg
  docs/img/its_magic.jpg
  docs/img/secretless_overview.jpg
  docs/img/secretless_overview.png
  docs/img/security_admin.jpg
Labels: implementing, in progress

#647 Adding featured images to blog posts / adding Go blog post
  docs/_layouts/blog.html
  docs/_layouts/post.html
  docs/_layouts/subpages.html
  docs/_posts/2018-09-03-announcing-secretless.md
  docs/_posts/2018-09-20-conversion-to-go-modules.md
  docs/_posts/2018-09-21-configuration-with-custom-resources.md
  docs/_posts/2018-12-06-meet-us-at-kubecon.md
  docs/_posts/2019-03-04-go.md
  docs/_posts/adding-new-handlers.md
  docs/_sass/_blog.scss
  docs/img/blog/go-gopher-illustration.jpg
  docs/img/blog/secretless_at_kubecon_2018.png
  docs/img/blog/secretless_logo_blog.jpg
Labels: implementing, in progress

#656 fixing broken link in footer
  docs/_data/navigation.yml
Labels: component/secretless-site

#659 Temporarily turn off SSH handler test
  test/ssh_handler/test
Labels: implementing, in progress

#652 104 update fast k8s tut
  demos/k8s-demo/01_create_db.sh
  demos/k8s-demo/01_security_admin_steps
  demos/k8s-demo/02_app_developer_steps
  demos/k8s-demo/02_configure_db.sh
  demos/k8s-demo/03_deploy_app.sh
  demos/k8s-demo/04_test_deployment.sh
  demos/k8s-demo/README.md
  demos/k8s-demo/admin_config.sh
  demos/k8s-demo/rotate_password.sh
  demos/k8s-demo/security_admin_secrets.sh
  demos/k8s-demo/utils.sh
Labels: in progress, reviewing

#662 Fix ssh handler test
  test/ssh_handler/Dockerfile.ssh_host
  test/ssh_handler/start
  test/ssh_handler/test
Labels: implementing, in progress

#660 Fix all non-TODO CodeClimate issues
  bin/abspath
  bin/build
  bin/build_darwin
  bin/build_release
  bin/build_website
  bin/check_website_links
  bin/codegen
  bin/cpu_profiling
  bin/prefill_changelog
  bin/publish
  bin/publish_website
  bin/test_benchmarks
  bin/test_demo
  demos/full-demo/build
  demos/full-demo/conjur/5_run_tls_frontend
  demos/full-demo/plaintext/4_run_tls_frontend
  demos/quick-start/bin/test
  demos/quick-start/docker/bin/entrypoint
Labels: in progress, reviewing

#664 Fix broken website publishing
  bin/publish_website
Labels: implementing, in progress

#654 103 note styling
  docs/_data/navigation.yml
  docs/_sass/_defaults.scss
  docs/docs/get_started/kubernetes_tutorial.md
Labels: implementing, in progress

#665 Update test vault command used to add secrets
  test/vault_provider/start
Labels: implemented, in progress

#668 document k8s secrets provider
  README.md
Labels: in progress, reviewing

#669 fix kubernetes secrets example in README
  README.md
Labels: in progress, reviewed

#670 Update CHANGELOG for beta release
  CHANGELOG.md
  VERSION
  demos/k8s-demo/02_app_developer_steps
  test/manual/k8s_crds/deploy
  test/manual/keychain_provider/README.md
Labels: implementing, in progress

#672 fix quick start docs so any psql CLI works
  README.md
  docs/_includes/quick_start.html
Labels: implementing, in progress
