Repository cyberark/secretless-broker, pull requests merged in 2019-01, with the labels that each got.

#577 Correct notes styling so that they match with the README
  CONTRIBUTING.md
Labels: component/secretless-broker, implemented, in progress

#578 555 Add healthchecks to broker
  CHANGELOG.md
  README.md
  cmd/secretless-broker/main.go
  docs/_data/navigation.yml
  docs/docs/reference/health-check/overview.md
  go.mod
  go.sum
  internal/app/secretless/proxy.go
  internal/pkg/util/health.go
  internal/pkg/util/health_test.go
Labels: implementing, in progress

#583 Update conjur-api-go dependency
  go.mod
  go.sum
Labels: implementing, in progress

#588 Bumping version to 0.6.1
  CHANGELOG.md
  VERSION
Labels: implementing, in progress

#594 Made more handlers/listeners not dump credentials in debug mode
  CHANGELOG.md
  internal/app/secretless/handlers/http/aws.go
  internal/app/secretless/handlers/mysql/backend.go
  internal/app/secretless/handlers/pg/backend.go
  internal/app/secretless/handlers/ssh/handler.go
  internal/app/secretless/handlers/sshagent/handler.go
  internal/app/secretless/listeners/http/listener.go
Labels: implementing, in progress

#596 Remove debug from all demos and examples
  cmd/secretless-broker/main.go
  demos/full-demo/conjur/docker-compose.yml
  demos/k8s-demo/etc/secretless.yml
  docs/docs/get_started/kubernetes_tutorial.md
  docs/docs/reference/handlers/http/aws.md
  test/aws_handler/secretless.yml
  test/conjur/secretless.dev.yml
  test/conjur/secretless.yml
  test/http_basic_auth/secretless.yml
  test/plugin/secretless.dev.yml
  test/plugin/secretless.yml
  test/ssh_agent_handler/secretless.dev.yml
  test/ssh_agent_handler/secretless.yml
  test/ssh_handler/secretless.yml
Labels: implementing, in progress

#597 Bumping version to 0.6.2
  CHANGELOG.md
  VERSION
Labels: implementing, in progress

#598 Made permissions fixes for OpenShift deployment
  CHANGELOG.md
  Dockerfile
Labels: implementing, in progress

#602 601 improve dev tests
  Dockerfile
  Dockerfile.dev
  Dockerfile.test
  bin/Dockerfile.codegen
  demos/full-demo/src/myapp/Dockerfile
  demos/full-demo/src/proxy_tls/Dockerfile
  go.mod
  go.sum
  test/pg_handler/README.md
  test/pg_handler/docker-compose.yml
  test/pg_handler/start
  test/pg_handler/test
  test/plugin/echo/Dockerfile
  test/util/test/types.go
Labels: implementing, in progress

#605 Important renames, style fixes, clarifications, and assorted refactors
  README.md
  go.sum
  internal/app/secretless/handlers/http/conjur.go
  internal/app/secretless/listeners/http/listener.go
  internal/app/summon/command/command.go
  internal/app/summon/command/run.go
  internal/pkg/plugin/manager.go
  internal/pkg/plugin/resolver.go
  internal/pkg/plugin/resolver_test.go
  pkg/secretless/config/config.go
  pkg/secretless/plugin/v1/connection_manager.go
  pkg/secretless/plugin/v1/event_notifier.go
  pkg/secretless/plugin/v1/resolver.go
  test/conjur/conjur_provider_test.go
  test/mysql_handler/pkg/run_test_case.go
  test/mysql_handler/tests/essentials_test.go
  test/mysql_handler/tests/ssl_test.go
  test/pg_handler/pkg/run_test_case.go
  test/pg_handler/tests/essentials_test.go
  test/pg_handler/tests/ssl_test.go
  test/plugin/example/conn_manager.go
  test/plugin/example/handler.go
  test/plugin/provider_test.go
  test/util/test/backend_configuration.go
  test/util/test/config_generator.go
  test/util/test/init.go
  test/util/test/types.go
Labels: implemented, in progress

#611 Remove go.sum hacks from Dockerfiles
  CONTRIBUTING.md
  Dockerfile
  Dockerfile.dev
  Dockerfile.test
Labels: implementing, in progress

#610 Zeroization proposal
  design/proposal-zeroization.md
Labels: implementing, in progress
